<a href="https://colab.research.google.com/github/SILVIAIRENE/Data-Scientist-Machine-Learning-Engineer-Introductory-Course/blob/master/Aplicaci%C3%B3n_de_productos_matriciales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problema 1: Producto matricial manual
El producto matricial de A y B se calcula multiplicando las filas de la matriz A por las columnas de la matriz B y sumando los productos.

Matrices:
A=
​

−1
4
7
​
  
2
−5
8
​
  
3
6
−9
​
  

​
B=

​
0
0
2
​
  
2
2
9
​
  
1
−8
−1
​
  

​


Cálculos:

Elemento (0,0) de C: Fila 0 de A por Columna 0 de B:
(−1⋅0)+(2⋅0)+(3⋅2)=0+0+6=6

Elemento (0,1) de C: Fila 0 de A por Columna 1 de B:
(−1⋅2)+(2⋅2)+(3⋅9)=−2+4+27=29

Elemento (0,2) de C: Fila 0 de A por Columna 2 de B:
(−1⋅1)+(2⋅−8)+(3⋅−1)=−1−16−3=−20

Elemento (1,0) de C: Fila 1 de A por Columna 0 de B:
(4⋅0)+(−5⋅0)+(6⋅2)=0+0+12=12

Elemento (1,1) de C: Fila 1 de A por Columna 1 de B:
(4⋅2)+(−5⋅2)+(6⋅9)=8−10+54=52

Elemento (1,2) de C: Fila 1 de A por Columna 2 de B:
(4⋅1)+(−5⋅−8)+(6⋅−1)=4+40−6=38

Elemento (2,0) de C: Fila 2 de A por Columna 0 de B:
(7⋅0)+(8⋅0)+(−9⋅2)=0+0−18=−18

Elemento (2,1) de C: Fila 2 de A por Columna 1 de B:
(7⋅2)+(8⋅2)+(−9⋅9)=14+16−81=−51

Elemento (2,2) de C: Fila 2 de A por Columna 2 de B:
(7⋅1)+(8⋅−8)+(−9⋅−1)=7−64+9=−48

Matriz resultante C:
C=

​
  
6
12
−18
​
  
29
52
−51
​
  
−20
38
−48
​
  

​




In [ ]:
#EJERCICIO 2
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Usando np.matmul()
c_matmul = np.matmul(a_ndarray, b_ndarray)
print("Resultado con np.matmul():\n", c_matmul)

# Usando np.dot()
c_dot = np.dot(a_ndarray, b_ndarray)
print("\nResultado con np.dot():\n", c_dot)

# Usando el operador @
c_at = a_ndarray @ b_ndarray
print("\nResultado con el operador @:\n", c_at)


Resultado con np.matmul():
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Resultado con np.dot():
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Resultado con el operador @:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [ ]:
#2
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calcular el elemento (0, 0) manualmente
c00 = (a_ndarray[0, 0] * b_ndarray[0, 0]) + \
      (a_ndarray[0, 1] * b_ndarray[1, 0]) + \
      (a_ndarray[0, 2] * b_ndarray[2, 0])

print(f"El elemento (0, 0) de la matriz resultante es: {c00}")

El elemento (0, 0) de la matriz resultante es: 6


In [ ]:
#3
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calcular el elemento (0, 0) manualmente
c00 = (a_ndarray[0, 0] * b_ndarray[0, 0]) + \
      (a_ndarray[0, 1] * b_ndarray[1, 0]) + \
      (a_ndarray[0, 2] * b_ndarray[2, 0])

print(f"Element (0, 0) of the resulting matrix is: {c00}")

Element (0, 0) of the resulting matrix is: 6


In [ ]:
#4
import numpy as np

def matrix_multiply(A, B):
    """
    Realiza la multiplicación de dos matrices A y B.

    Args:
      A (np.ndarray): La primera matriz.
      B (np.ndarray): La segunda matriz.

    Returns:
      np.ndarray: La matriz resultante del producto A * B.
    """
    if A.shape[1] != B.shape[0]:
        raise ValueError("The number of columns in A must be equal to the number of rows in B.")

    num_rows_A, num_cols_A = A.shape
    num_rows_B, num_cols_B = B.shape

    C = np.zeros((num_rows_A, num_cols_B))


    for i in range(num_rows_A):
        for j in range(num_cols_B):
            for k in range(num_cols_A):
                C[i, j] += A[i, k] * B[k, j]

    return C

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

result_matrix = matrix_multiply(a_ndarray, b_ndarray)
print("Result:\n", result_matrix)

Resultado de la función matrix_multiply:
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [ ]:
#5
import numpy as np

def safe_matrix_multiply(A, B):
    """
    Realiza la multiplicación de matrices de forma segura.

    Args:
      A (np.ndarray): La primera matriz.
      B (np.ndarray): La segunda matriz.

    Returns:
      np.ndarray: La matriz resultante.
    """
    if A.shape[1] != B.shape[0]:
        print("Error: El número de columnas de la matriz A no coincide con el número de filas de la matriz B.")
        return None

    num_rows_A, num_cols_A = A.shape
    num_rows_B, num_cols_B = B.shape
    C = np.zeros((num_rows_A, num_cols_B))

    for i in range(num_rows_A):
        for j in range(num_cols_B):
            for k in range(num_cols_A):
                C[i, j] += A[i, k] * B[k, j]

    return C

# Ejemplo con matrices D y E donde la multiplicación no está definida
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

safe_matrix_multiply(d_ndarray, e_ndarray)

Error: El número de columnas de la matriz A no coincide con el número de filas de la matriz B.


In [ ]:
#6
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# Transposición de la matriz D para poder multiplicarla por E
d_transposed = d_ndarray.T

print("Matriz D original:\n", d_ndarray)
print("\nMatriz D transpuesta:\n", d_transposed)

# La multiplicación de D.T por E es posible
# (Filas de D.T = 3, Columnas de E = 2)
# Las dimensiones son (3x2) * (2x3), lo que produce una matriz (3x3)
product_de_transposed = d_transposed @ e_ndarray
print("\nProducto de D.T @ E:\n", product_de_transposed)

Matriz D original:
 [[-1  2  3]
 [ 4 -5  6]]

Matriz D transpuesta:
 [[-1  4]
 [ 2 -5]
 [ 3  6]]

Producto de D.T @ E:
 [[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
